### ISSUE TITLE
Example not Working?

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/openPMD-converter-GDF#5]
Hi @KseniaBastrakova,

@ChristopherMayes tries to use the example script and it seems not to work. Can you please assist him?
Thanks, Axel

```
 $python gdf_to_hdf.py examples/example_1.gdf examples/example_1.h5
Destination .hdf directory not specified. Defaulting to examples/example_1.hdf
Converting .gdf to .hdf file
unknown datatype of value
name= b'\x00\x00\x00\x00x\x00\xc5\xb9\xfe\x7f\x00\x00'
type= 32766
size= 2051
unknown datatype of value
name= b'\x00\x00\x00\x00x\x00\xc5\xb9\xfe\x7f\x00\x00'
type= 32766
size= 2051
Traceback (most recent call last):
  File "gdf_to_hdf.py", line 589, in <module>
    main(file_names)
  File "gdf_to_hdf.py", line 584, in main
    converter(gdf_path, hdf_path)
  File "gdf_to_hdf.py", line 577, in converter
    gdf_to_hdf(gdf_file, hdf_file)
  File "gdf_to_hdf.py", line 551, in gdf_to_hdf
    gdf_file_to_hdf_file(gdf_file, hdf_file)
  File "gdf_to_hdf.py", line 487, in gdf_file_to_hdf_file
    add_positionOffset(subparticles_group, size)
  File "gdf_to_hdf.py", line 431, in add_positionOffset
    positionOffset_group = particles_group.require_group('positionOffset')
AttributeError: 'NoneType' object has no attribute 'require_group'
```

**Comment by ax3l** [comment]
@ChristopherMayes whats the version of `h5py` you are using? `python -c "import h5py; print(h5py.__version__)"`

**Comment by KseniaBastrakova** [comment]
Thanks for bug report.  I could reproduce it. Working on a fix.

**Comment by ChristopherMayes** [comment]
I have:
HDF5: 1.10.4
h5py: 2.9.0
macOS Mojave (latest)
python 3.6.8

**Comment by KseniaBastrakova** [comment]
Fixed

**Comment by ChristopherMayes** [comment]
It runs, but does not create the output file (test.h5):
python gdf_to_hdf.py examples/example_1.gdf test.h5

Also, I had to add .py to the name of the script. The README has:
python gdf_to_hdf examples/example_1.gdf examples/example_1.h5

**Comment by KseniaBastrakova** [comment]
oops) no, it should work

**Comment by ax3l** [comment]
*now? :)

**Comment by ChristopherMayes** [comment]
Okay, looks like it works now. And, it works on my own gpt files. 

However, it doesn't look like the units are right for momentum. What units are they supposed to be? From what I can tell, momentum/x is being set to gamma*beta_x, which is dimensionless. 

MKS units should be kg*m/s, with a proper factor to convert p_x = mass*c_light*gamma*beta_x

**Comment by ax3l** [comment]
How are the origin units in the GDF file again? Are they MKS? Looks like we add proper dimension meta data but don't scale accordingly yet.

**Comment by ChristopherMayes** [comment]
GPT normally records relativistic gamma and beta vector components, labeled:
 G          Bx          By          Bz

Proper momentum/x would be:
mass  cLight G  Bx

For an electron, m_e c = 2.73092449 *10^-22 kg * m / s

**Comment by ax3l** [comment]
Excellent, that's just what we have to put in `unitSI`.

@KseniaBastrakova for particles, the [`particleName/`](https://github.com/openPMD/openPMD-standard/blob/latest/STANDARD.md#particle-records) group seems to be still missing when I run the GDF to HDF5 converter.

During convert, we can either keep `unitSI` to `1.0` and convert the momentum, since we copy the data anyway, or we sort out by same-mass to create individual species.

**Comment by KseniaBastrakova** [comment]
Thanks for bug report. I could reproduce it. Working on a fix.

**Comment by KseniaBastrakova** [comment]
Fixed. I added m_species c in the unitSI. And for parclename/ i implemented classification into electrons, protons and electrons. (As advice by @BeyondEspresso)
